# Generated by Django 4.0.4 on 2022-06-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0002_alter_attacktechnique_attack_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninja',
            name='invocations',
            field=models.ManyToManyField(blank=True, to='village.invocation'),
        ),
    ]
