# Generated by Django 4.0.4 on 2022-06-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0003_alter_ninja_invocations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='parchments',
            field=models.ManyToManyField(blank=True, to='village.parchment'),
        ),
    ]
