# Generated by Django 4.0.4 on 2022-06-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0005_remove_team_members_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninja',
            name='nickname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
