# Generated by Django 4.0.3 on 2022-06-09 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0006_alter_ninja_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village.jounin'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village.client'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village.team'),
        ),
    ]
